### ISSUE TITLE
Back Inventory Slot

### ISSUE THREAD

**Issue by thejollygreenogre** [ChampionAsh5357/Custom-Ideas#2]
A back inventory slot that can render shields and weapons. The elytra would also work in the slot so you can use a chestplate with it. There could also be a button to quickly change what item is in it like the offhand

**Comment by thejollygreenogre** [comment]
How's it coming along? It doesn't look like you get too many suggestions for this so hopefully pretty well. Do you think you could also restrict the offhand for weapons like axes? Irl axes can't really be used with one hand. I hope I'm not adding to much to your plate.

**Comment by ChampionAsh5357** [comment]
You're not. I'm right now remaking the player class and attaching a capability to implement. For the axe restriction, all I have to do is change the slot acceptance. I should hopefully be done by the end of the month, but a lot of finals for summer courses are happening over the next week so I can't make any promises. However, I can promise it will be done by the end of July.

**Comment by thejollygreenogre** [comment]
Cool, the "prototype" works like a charm. I've been tinkering with it and I'm also adding a hand slot for gauntlets in my mod. Are you going to make the final version of it work in the creative inventory too?

**Comment by ChampionAsh5357** [comment]
Yeah, right now I'm just trying to get the inventory to persist.

**Comment by ChampionAsh5357** [comment]
The code is done. I rewrote the entire thing using capabilities properly because rewriting the entire inventory would cause way too many problems that I don't really want to deal with.  So instead I added a button that would take you to the custom inventory because I figured I could expand the inventory later with custom arm and leg slots or maybe something else. Similar to the survival tabs, it will only be able to be accessed in survival mode because of inventory changing.  There will be an image on the button to represent the changing inventory whenever I figure out a look for it.  The only thing that I couldn't really implement is the Elytra because the Minecraft code checks if the Elytra is in the armor slot so I would have to write a workaround.  You can still put on the Elytra, it just won't do anything other than aesthetic appeal.
